import type { Metadata } from "next";
import "./globals.css";
import SubRootLayout from "@/app/sub-root-layout";
import NextTopLoader from "nextjs-toploader";
import { getIronSession } from "iron-session";
import { agentSession, sessionOptions } from "@/session.config";
import { cookies } from "next/headers";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getIronSession<agentSession>(cookies(), sessionOptions);
  return (
    <html lang="fa" dir="rtl">
      <body>
        <NextTopLoader showSpinner={false} />
        {session.verified ? (
          <SubRootLayout>{children}</SubRootLayout>
        ) : (
          children
        )}
      </body>
    </html>
  );
}
